### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by scabbiaza** [ivan-kleshnin/tetris-cyclejs#2]
Hi!

Have some comments and questions about installation
1. `cyclejs-stream` is missed in `package.json`
2.  Should I run `source bin/install`? only first time?
3.  Could you pls add URL what to watch to the README
4. On `http://localhost:2992/` I see list of the folders and files from the repo folder
5. On `http://localhost:2992/src/` I see game in Pause mode. Nothing happens.
6. Is this repo should re-build after changing css? Doesn't do it now.
7. On template changes it doesn't run re-build process also.
8. There are still links in the layout on the including `font-awesome` & `bootstrap` libs

**Comment by ivan-kleshnin** [comment]
> cyclejs-stream is missed in package.json

I tried to use this lib and was bitten by bugs so I decided to use basic Rx Subjects instead. 
This dependency is now removed.

> Should I run source bin/install? only first time?

Good question. It should be run first time and if **webpack** / **webpack-dev-server** or **mocha** were reinstalled. I dunno how to approach this better for now.

> Could you pls add URL what to watch to the README

Should be open from HTML directly. I will add comment in README.

> Is this repo should re-build after changing css? Doesn't do it now.

No.

> On template changes it doesn't run re-build process also.

There are no "templates" because there is no "backend".

> There are still links in the layout on the including font-awesome & bootstrap libs

Fixed, thanks. I messed it up with my dev branches :disappointed:
